{% set name = "rmlst" %}
{% set version = "0.0.6" %}

package:
  name: "{{ name | lower }}"
  version: "{{ version }}"

source:
  # Example: Download the source tarball from GitHub.
  url: https://github.com/ssi-dk/rmlst/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 6b37c83a2ee34a3583bac3bf62d80d07294eb18295e80027e1cf3c7a132b1b43

build:
  number: 0

requirements:
  host:
    - python
    - requests
  run:
    - python
    - requests

test:
  commands:
    - rmlst -h

about:
  home: https://github.com/ssi-dk/{{ name }}
  license: MIT
  summary: "rMLST does science"

extra:
  recipe-maintainers:
    - githubz0r


