{% set name = "rmlst" %}
{% set version = "0.0.4" %}

package:
  name: "{{ name | lower }}"
  version: "{{ version }}"

source:
  # Example: Download the source tarball from GitHub.
  url: https://github.com/ssi-dk/rmlst/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0a940335964bc31fc76c70b67728f5e6912c7aa0aceaf3cc4643c89b27c50859

build:
  number: 0

requirements:
  host:
    - python
  run:
    - python

test:
  commands:
    - rmlst -h

about:
  home: https://github.com/ssi-dk/{{ name }}
  license: MIT
  summary: "rMLST does science"

extra:
  recipe-maintainers:
    - githubz0r


